googleads/googleads-mobile-ios-mediation

- adapters/Vungle/VungleAdapter/vungleHelper.m
Updated Adapter files to be compatible with Vungle SDK 5.3.0
> Compatible with Vungle SDK version 5.3.0.

- adapters/Maio/CHANGELOG.md
- adapters/Maio/MaioAdapter/GADMMaioConstants.h
- adapters/Maio/MaioAdapter/GADMMaioDelegateAggregate.m
Fixed the problem that objects are released at unintended timing in for-in
> Fix exception in maio adapter

- adapters/Vungle/Public/Headers/VungleRouterConsent.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleInterstitial.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRewardBasedVideoAd.m
- adapters/Vungle/VungleAdapter/VungleRouter.h
- adapters/Vungle/VungleAdapter/VungleRouter.m
- adapters/Vungle/VungleAdapter/VungleRouterConsent.m
Exposed static method to set consent as per of AdMob request
> Compatible with iOS SDK 6.2.0 - phase2

- adapters/Maio/CHANGELOG.md
- adapters/Maio/MaioAdapter/GADMMaioConstants.h
- adapters/Maio/MaioAdapter/GADMMaioInterstitialAdapter.m
- adapters/Maio/MaioAdapter/GADMMaioMaioInstanceRepository.h
- adapters/Maio/MaioAdapter/GADMMaioMaioInstanceRepository.m
- adapters/Maio/MaioAdapter/GADMMaioRewardedAdapter.m
- Update adapter version.
- Fixed an issue where maio adapter might fail if multiple MediaIds are provided from AdMob.
> Update maio Adapter 1.4.1.0

- adapters/IronSource/CHANGELOG.md
- adapters/IronSource/IronSourceAdapter.xcodeproj/project.pbxproj
- adapters/IronSource/IronSourceAdapter/GADMAdapterIronSource.m
- adapters/IronSource/IronSourceAdapter/GADMAdapterIronSourceConstants.h
- adapters/IronSource/IronSourceAdapter/GADMAdapterIronSourceDelegate.h
- adapters/IronSource/IronSourceAdapter/GADMAdapterIronSourceRewarded.h
- adapters/IronSource/IronSourceAdapter/GADMAdapterIronSourceRewardedAd.h
- adapters/IronSource/IronSourceAdapter/GADMAdapterIronSourceRewardedAd.m
- adapters/IronSource/IronSourceAdapter/GADMAdapterIronSourceUtils.h
- adapters/IronSource/IronSourceAdapter/GADMAdapterIronSourceUtils.m
- adapters/IronSource/IronSourceAdapter/GADMediationAdapterIronSource.m
- adapters/IronSource/IronSourceAdapter/ISMediationManager.h
- adapters/IronSource/IronSourceAdapter/ISMediationManager.m
Updating Ironsource Adapter to version 6.8.3.0.
> Updating Ironsource Adapter to handle multiple interstitial requests.

- adapters/Unity/UnityAdapter/GADMAdapterUnity.m
- adapters/Unity/UnityAdapter/GADMAdapterUnityProtocol.h
- adapters/Unity/UnityAdapter/GADMAdapterUnityRewardedAd.m
- adapters/Unity/UnityAdapter/GADMAdapterUnitySingleton.h
- adapters/Unity/UnityAdapter/GADMAdapterUnitySingleton.m
- adapters/Unity/UnityAdapter/GADMediationAdapterUnity.m
Updating Unity adapter to support Unity Ads SDK 3.1.0.
> Updating Unity adapter to support Unity Ads SDK 3.1.0.

- adapters/Facebook/CHANGELOG.md
- adapters/Facebook/FacebookAdapter/GADMAdapterFacebookConstants.h
Prepare Facebook Audience Network release 5.4.0
> Updating Facebook adapter to version 5.4.0.0

- adapters/Tapjoy/TapjoyAdapter.xcodeproj/project.pbxproj
- adapters/Tapjoy/TapjoyAdapter/GADMAdapterTapjoy.m
- adapters/Tapjoy/TapjoyAdapter/GADMAdapterTapjoySingleton.h
- adapters/Tapjoy/TapjoyAdapter/GADMAdapterTapjoySingleton.m
- adapters/Tapjoy/TapjoyAdapter/GADMRewardedAdTapjoy.m
- adapters/Tapjoy/TapjoyAdapter/GADMediationAdapterTapjoy.h
- adapters/Tapjoy/TapjoyAdapter/GADMediationAdapterTapjoy.m
- adapters/Tapjoy/TapjoyAdapter/OpenBidding/GADMRTBInterstitialRendererTapjoy.h
- adapters/Tapjoy/TapjoyAdapter/OpenBidding/GADMRTBInterstitialRendererTapjoy.m
Merging OB version of the Tapjoy adapter with the public version.
> Merging OB version of the Tapjoy adapter with the public version.

- adapters/AdColony/AdColonyAdapter/GADMAdapterAdColonyHelper.h
- adapters/AdColony/AdColonyAdapter/GADMAdapterAdColonyHelper.m
- adapters/AdColony/AdColonyAdapter/GADMediationAdapterAdColony.m
- adapters/AdColony/CHANGELOG.md
Adding checks to the credentials before initializing AdColony SDK.
> Adding checks to the credentials before initializing AdColony SDK.

- adapters/Facebook/BuildScript/Script_Validate.sh
> Internal change.

- adapters/MoPub/CHANGELOG.md
- adapters/MoPub/MoPubAdapter/GADMAdapterMoPub.h
- adapters/MoPub/MoPubAdapter/GADMAdapterMoPub.m
- adapters/MoPub/MoPubAdapter/GADMAdapterMoPubSingleton.h
- adapters/MoPub/MoPubAdapter/GADMAdapterMoPubSingleton.m
- adapters/MoPub/MoPubAdapter/GADMAdapterMoPubUtils.m
- adapters/MoPub/MoPubAdapter/GADMMoPubRewardedAd.h
- adapters/MoPub/MoPubAdapter/GADMMoPubRewardedAd.m
- adapters/MoPub/MoPubAdapter/GADMediationAdapterMoPub.h
- adapters/MoPub/MoPubAdapter/GADMediationAdapterMoPub.m
- adapters/MoPub/MoPubAdapter/MoPubAdapterConstants.h
- adapters/MoPub/MoPubAdapter/MoPubAdapterMediatedNativeAd.h
- adapters/MoPub/MoPubAdapter/MoPubAdapterMediatedNativeAd.m
Updating MoPub adapter to compile against MoPub SDK 5.8.0
> Updating MoPub adapter to compile against MoPub SDK 5.8.0

- adapters/Facebook/CHANGELOG.md
- adapters/Facebook/FacebookAdapter/GADMAdapterFacebookConstants.h
Updated for 5.5.1 FAN SDK version.
> Update Facebook adapters for 5.5.1

- adapters/AppLovin/AppLovinAdapter.xcodeproj/project.pbxproj
- adapters/AppLovin/AppLovinAdapter/GADMAdapterAppLovin.h
- adapters/AppLovin/AppLovinAdapter/GADMAdapterAppLovin.m
- adapters/AppLovin/AppLovinAdapter/GADMAdapterAppLovinBannerDelegate.h
- adapters/AppLovin/AppLovinAdapter/GADMAdapterAppLovinBannerDelegate.m
- adapters/AppLovin/AppLovinAdapter/GADMAdapterAppLovinConstant.h
- adapters/AppLovin/AppLovinAdapter/GADMAdapterAppLovinConstant.m
- adapters/AppLovin/AppLovinAdapter/GADMAdapterAppLovinInterstitialDelegate.h
- adapters/AppLovin/AppLovinAdapter/GADMAdapterAppLovinInterstitialDelegate.m
- adapters/AppLovin/AppLovinAdapter/GADMAdapterAppLovinMediationManager.h
- adapters/AppLovin/AppLovinAdapter/GADMAdapterAppLovinMediationManager.m
- adapters/AppLovin/AppLovinAdapter/GADMAdapterAppLovinNative.m
- adapters/AppLovin/AppLovinAdapter/GADMAdapterAppLovinUtils.h
- adapters/AppLovin/AppLovinAdapter/GADMAdapterAppLovinUtils.m
- adapters/AppLovin/AppLovinAdapter/GADMAppLovinExtraAssets.m
- adapters/AppLovin/AppLovinAdapter/GADMAppLovinMediatedNativeUnifiedAd.h
- adapters/AppLovin/AppLovinAdapter/GADMAppLovinMediatedNativeUnifiedAd.m
- adapters/AppLovin/AppLovinAdapter/GADMediationAdapterAppLovin.m
- adapters/AppLovin/AppLovinAdapter/OpenBidding/GADMAdapterAppLovinRewardedRenderer.h
- adapters/AppLovin/AppLovinAdapter/OpenBidding/GADMAdapterAppLovinRewardedRenderer.m
- adapters/AppLovin/AppLovinAdapter/OpenBidding/GADMAppLovinRewardedDelegate.h
- adapters/AppLovin/AppLovinAdapter/OpenBidding/GADMAppLovinRewardedDelegate.m
- adapters/AppLovin/AppLovinAdapter/OpenBidding/GADMRTBAdapterAppLovinBannerRenderer.h
- adapters/AppLovin/AppLovinAdapter/OpenBidding/GADMRTBAdapterAppLovinBannerRenderer.m
- adapters/AppLovin/AppLovinAdapter/OpenBidding/GADMRTBAdapterAppLovinInterstitialRenderer.h
- adapters/AppLovin/AppLovinAdapter/OpenBidding/GADMRTBAdapterAppLovinInterstitialRenderer.m
- adapters/AppLovin/CHANGELOG.md
* Updating AppLovin adapter to be compatible with AppLovin SDK version 6.8.1.
* Added code to properly handle the completion handlers after called.
* Linting the code to follow Google's Objective-C code-style.
> * Updating AppLovin adapter to be compatible with AppLovin SDK version 6.8.1.

- adapters/AppLovin/AppLovinAdapter/GADMAdapterAppLovinConstant.h
- adapters/AppLovin/AppLovinAdapter/GADMAdapterAppLovinConstant.m
- adapters/AppLovin/AppLovinAdapter/GADMAdapterAppLovinMediationManager.h
- adapters/AppLovin/AppLovinAdapter/GADMAdapterAppLovinMediationManager.m
- adapters/AppLovin/AppLovinAdapter/GADMediationAdapterAppLovin.m
- adapters/AppLovin/AppLovinAdapter/OpenBidding/GADMAdapterAppLovinRewardedRenderer.h
- adapters/AppLovin/AppLovinAdapter/OpenBidding/GADMAdapterAppLovinRewardedRenderer.m
- adapters/AppLovin/AppLovinAdapter/OpenBidding/GADMAppLovinRewardedDelegate.m
Added code which prevents AppLovin adapter to request multiple ads using the same zone identifier.
> Added code which prevents AppLovin adapter to request multiple ads using the same zone identifier.

- adapters/AdColony/AdColonyAdapter/GADMAdapterAdColony.h
- adapters/AdColony/AdColonyAdapter/GADMAdapterAdColony.m
- adapters/AdColony/AdColonyAdapter/GADMAdapterAdColonyConstants.h
- adapters/AdColony/AdColonyAdapter/GADMAdapterAdColonyHelper.h
- adapters/AdColony/AdColonyAdapter/GADMAdapterAdColonyHelper.m
- adapters/AdColony/AdColonyAdapter/GADMAdapterAdColonyInitializer.h
- adapters/AdColony/AdColonyAdapter/GADMAdapterAdColonyInitializer.m
- adapters/AdColony/AdColonyAdapter/GADMediationAdapterAdColony.m
- adapters/AdColony/AdColonyAdapter/OpenBidding/GADMAdapterAdColonyRewardedRenderer.h
- adapters/AdColony/AdColonyAdapter/OpenBidding/GADMAdapterAdColonyRewardedRenderer.m
- adapters/AdColony/AdColonyAdapter/OpenBidding/GADMAdapterAdColonyRtbInterstitialRenderer.m
- adapters/AdColony/Public/Headers/GADMediationAdapterAdColony.h
* Updating AdColony adapter to version 3.3.8.1.0.
* Added code to properly handle the completion handlers after called.
* Linting the code to follow Google's Objective-C code-style.
> * Updating AdColony adapter to version 3.3.8.1.0.

- adapters/Maio/CHANGELOG.md
- adapters/Maio/MaioAdapter/GADMMaioConstants.h
> Update maio adapter v1.5.0.0

- adapters/Facebook/CHANGELOG.md
- adapters/Facebook/FacebookAdapter/GADMAdapterFacebookConstants.h
> Adapters for 5.6 FAN

- adapters/VerizonMedia/VerizonMediaAdapter/Native/GADMAdapterVerizonNativeAd.m
- adapters/VerizonMedia/VerizonMediaAdapter/Rewarded/GADMAdapterVerizonRewardedAd.m
Removing unwanted properties in the Verizon adapter.
> Removing unwanted properties in the Verizon adapter.

- adapters/Facebook/FacebookAdapter/GADFBUtils.h
- adapters/Facebook/FacebookAdapter/GADFBUtils.m
- adapters/Facebook/FacebookAdapter/GADMAdapterFacebook.m
- adapters/Facebook/FacebookAdapter/GADMediationAdapterFacebook.m
Updated Facebook adapter to their latest API to pass the COPPA info.
> Updated Facebook adapter to their latest API to pass the COPPA info.

- adapters/AdColony/AdColonyAdapter/OpenBidding/GADMAdapterAdColonyRTBInterstitialRenderer.m
- adapters/AdColony/AdColonyAdapter/OpenBidding/GADMAdapterAdColonyRewardedRenderer.m
Adding code to re-request ads for OB requests when the AdColony ad expires.
> Adding code to re-request ads for OB requests when the AdColony ad expires.

- adapters/Facebook/FacebookAdapter/GADFBNativeBannerAd.m
- adapters/Facebook/FacebookAdapter/GADFBUnifiedNativeAd.m
- adapters/Facebook/FacebookAdapter/OpenBidding/GADFBNativeRenderer.m
Add native banner icon support using 5.7.0.0.
> Add native banner icon support using 5.7.0.0.

- adapters/Facebook/FacebookAdapter/OpenBidding/GADFBBannerRenderer.m
- adapters/Facebook/FacebookAdapter/OpenBidding/GADFBInterstitialRenderer.m
- adapters/Facebook/FacebookAdapter/OpenBidding/GADFBNativeRenderer.m
- adapters/Facebook/FacebookAdapter/OpenBidding/GADFBRewardedRenderer.m
Update the Facebook Adapter to store a boolean state for whether it started presenting.
> Update the Facebook Adapter to store a boolean state for whether it started presenting.

- adapters/Unity/UnityAdapter/GADMAdapterUnitySingleton.m
Add `@synchronized` block in `stopTrackingDelegate` to prevent potential multi-thread issue
> Add synchronized block in stopTrackingDelegate

- adapters/Unity/CHANGELOG.md
- adapters/Unity/UnityAdapter.xcodeproj/project.pbxproj
- adapters/Unity/UnityAdapter/GADMAdapterUnity.m
- adapters/Unity/UnityAdapter/GADMAdapterUnityBannerAd.m
- adapters/Unity/UnityAdapter/GADMAdapterUnityConstants.h
- adapters/Unity/UnityAdapter/GADMAdapterUnityProtocol.h
- adapters/Unity/UnityAdapter/GADMAdapterUnityRewardedAd.m
- adapters/Unity/UnityAdapter/GADMAdapterUnitySingleton.m
- adapters/Unity/UnityAdapter/GADMAdapterUnityUtils.h
- adapters/Unity/UnityAdapter/GADMAdapterUnityUtils.m
- adapters/Unity/UnityAdapter/GADMediationAdapterUnity.h
- adapters/Unity/UnityAdapter/GADMediationAdapterUnity.m
Unity iOS Standardized Adapter Errors
> Unity iOS Standardized Adapter Errors

- adapters/Vungle/VungleAdapter/GADMAdapterVungleInterstitial.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRewardedAd.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
Fix potential adapter timeout code paths in the Vungle Adapter
> Fix potential adapter timeout code paths in the Vungle Adapter

- adapters/Facebook/CHANGELOG.md
- adapters/Facebook/FacebookAdapter.xcodeproj/project.pbxproj
- adapters/Facebook/FacebookAdapter/GADMAdapterFacebook.m
- adapters/Facebook/FacebookAdapter/GADMediationAdapterFacebook.m
- adapters/Facebook/FacebookAdapter/OpenBidding/GADFBRewardedInterstitialRenderer.h
- adapters/Facebook/FacebookAdapter/OpenBidding/GADFBRewardedInterstitialRenderer.m
- adapters/Facebook/FacebookAdapter/OpenBidding/GADFBRewardedRenderer.m
Facebook Rewarded Interstitial iOS Adapter
> Facebook Rewarded Interstitial iOS Adapter

- adapters/InMobi/CHANGELOG.md
- adapters/InMobi/InMobiAdapter.xcodeproj/project.pbxproj
- adapters/InMobi/InMobiAdapter/GADMAdapterInMobi.m
- adapters/InMobi/InMobiAdapter/GADMAdapterInMobiInitializer.h
- adapters/InMobi/InMobiAdapter/GADMAdapterInMobiInitializer.m
- adapters/InMobi/InMobiAdapter/GADMAdapterInMobiRewardedAd.m
- adapters/InMobi/InMobiAdapter/GADMAdapterInMobiUtils.h
- adapters/InMobi/InMobiAdapter/GADMAdapterInMobiUtils.m
- adapters/InMobi/InMobiAdapter/GADMInMobiConsent.m
- adapters/InMobi/InMobiAdapter/GADMediationAdapterInMobi.h
- adapters/InMobi/InMobiAdapter/GADMediationAdapterInMobi.m
Verified InMobi iOS adapter compatibility with InMobi SDK 9.0.6
> Verified InMobi iOS adapter compatibility with InMobi SDK 9.0.6

- adapters/Tapjoy/TapjoyAdapter.xcodeproj/project.pbxproj
- adapters/Tapjoy/TapjoyAdapter/GADMAdapterTapjoy.m
- adapters/Tapjoy/TapjoyAdapter/GADMAdapterTapjoyDelegate.h
- adapters/Tapjoy/TapjoyAdapter/GADMAdapterTapjoySingleton.m
- adapters/Tapjoy/TapjoyAdapter/GADMAdapterTapjoyUtils.h
- adapters/Tapjoy/TapjoyAdapter/GADMAdapterTapjoyUtils.m
- adapters/Tapjoy/TapjoyAdapter/GADMRewardedAdTapjoy.m
- adapters/Tapjoy/TapjoyAdapter/GADMediationAdapterTapjoy.h
- adapters/Tapjoy/TapjoyAdapter/GADMediationAdapterTapjoy.m
- adapters/Tapjoy/TapjoyAdapter/OpenBidding/GADMRTBInterstitialRendererTapjoy.m
TapjoyAdapter iOS Standardized Adapter Errors.
> TapjoyAdapter iOS Standardized Adapter Errors.

- adapters/Vungle/VungleAdapter.xcodeproj/project.pbxproj
- adapters/Vungle/VungleAdapter/GADMAdapterVungleBanner.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleBanner.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleBannerRequest.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleDelegate.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleInterstitial.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleInterstitial.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRewardedAd.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleUtils.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleUtils.m
- adapters/Vungle/VungleAdapter/GADMediationAdapterVungle.h
- adapters/Vungle/VungleAdapter/VungleAdNetworkExtras.m
Refactored the Vungle iOS adapter's banner ad implementation.
> Refactored the Vungle iOS adapter's banner ad implementation.

- adapters/Fyber/CHANGELOG.md
- adapters/Fyber/FyberAdapter/GADMAdapterFyberConstants.h
- adapters/Fyber/FyberAdapter/GADMAdapterFyberExtras.h
- adapters/Fyber/FyberAdapter/GADMAdapterFyberExtras.m
- adapters/Fyber/FyberAdapter/GADMAdapterFyberUtils.h
- adapters/Fyber/FyberAdapter/GADMAdapterFyberUtils.m
- adapters/Fyber/FyberAdapter/GADMediationAdapterFyber.m
1. Updating Fyber Adapter to version 7.6.4
2. Added Fyber extra class
> Updating Fyber Adapter to version 7.6.4

- adapters/MoPub/MoPubAdapter/GADMAdapterMopubUnifiedNativeAd.m
Fixed incompatible type assigning error.
> Fixed incompatible type assigning error.

- adapters/MyTarget/MyTargetAdapter.xcodeproj/project.pbxproj
- adapters/MyTarget/MyTargetAdapter/GADMAdapterMyTargetConstants.h
- adapters/MyTarget/MyTargetAdapter/GADMAdapterMyTargetConstants.m
- adapters/MyTarget/MyTargetAdapter/GADMAdapterMyTargetUtils.m
Improved compatibility of adaptive banners (validate min/max height)
Improved constants file
> Updating myTarget iOS Adapter

- adapters/Fyber/FyberAdapter/GADMAdapterFyberBannerAd.m
- adapters/Fyber/FyberAdapter/GADMAdapterFyberInterstitialAd.m
- adapters/Fyber/FyberAdapter/GADMAdapterFyberRewardedAd.m
- adapters/Fyber/FyberAdapter/GADMAdapterFyberUtils.h
- adapters/Fyber/FyberAdapter/GADMAdapterFyberUtils.m
- adapters/Fyber/FyberAdapter/GADMediationAdapterFyber.m
Updated the Fyber Marketplace iOS adapter to use their new initialization APIs.
> Updated the Fyber Marketplace iOS adapter to use their new initialization APIs.

- adapters/Vungle/CHANGELOG.md
- adapters/Vungle/VungleAdapter/GADMAdapterVungleBanner.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleConstants.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleDelegate.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleInterstitial.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRewardedAd.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
This version of the adapter has been certified with Vungle 6.9.1 SDK.
> Release 6.9.1.0 Vungle AdMob Adapter

- adapters/IronSource/CHANGELOG.md
- adapters/IronSource/IronSourceAdapter/GADMediationAdapterIronSource.m
Adding RewardedInterstitial Ad support for IronSource iOS Adapter.
> Adding RewardedInterstitial Ad support for IronSource iOS Adapter.

- adapters/AdColony/AdColonyAdapter/GADMAdapterAdColonyInitializer.m
- adapters/AdColony/AdColonyAdapter/GADMediationAdapterAdColony.m
- adapters/AdColony/AdColonyAdapter/OpenBidding/GADMAdapterAdColonyRTBBannerRenderer.h
- adapters/AdColony/AdColonyAdapter/OpenBidding/GADMAdapterAdColonyRTBBannerRenderer.m
Cleanup from AdColony iOS Open Bidding Banner PR
> Cleanup from AdColony iOS Open Bidding Banner PR

- adapters/VerizonMedia/CHANGELOG.md
- adapters/VerizonMedia/VerizonMediaAdapter/GADMAdapterVerizonConstants.h
This update for SE v1.14.1 is ready to review, thanks!
> Update to Verizon SE v1.14.1

- adapters/Vungle/VungleAdapter/GADMAdapterVungleConstants.h
- Verified compatibility with Vungle SDK 6.10.3.
> Vungle mediation adapter 6.10.3.0 release

- adapters/MyTarget/CHANGELOG.md
- adapters/MyTarget/MyTargetAdapter/GADMAdapterMyTarget.m
- adapters/MyTarget/MyTargetAdapter/GADMAdapterMyTargetConstants.m
- adapters/MyTarget/MyTargetAdapter/GADMAdapterMyTargetExtras.m
- adapters/MyTarget/MyTargetAdapter/GADMAdapterMyTargetMediatedUnifiedNativeAd.m
- adapters/MyTarget/MyTargetAdapter/GADMAdapterMyTargetNative.m
- adapters/MyTarget/MyTargetAdapter/GADMAdapterMyTargetRewardedAd.m
- adapters/MyTarget/MyTargetAdapter/GADMAdapterMyTargetUtils.h
- adapters/MyTarget/MyTargetAdapter/GADMAdapterMyTargetUtils.m
- adapters/MyTarget/Public/Headers/GADMAdapterMyTargetExtras.h
Fixed minor bug in Native adapter (disable images loading)
Supported parameters in Extras.
Supported Extras in Rewarded ads.
> Updating myTarget iOS Adapter.

- adapters/Vungle/Public/Headers/VungleAdNetworkExtras.h
- adapters/Vungle/VungleAdapter.xcodeproj/project.pbxproj
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleInterstitial.m
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleNativeAd.h
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleNativeAd.m
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleRewardedAd.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleBanner.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleConstants.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleDelegate.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleInterstitial.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRewardBasedVideoAd.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
- adapters/Vungle/VungleAdapter/GADMediationAdapterVungle.m
- Verified compatibility with Vungle SDK 6.11.0
- Native ads support.
- Coppa Support.
> Vungle mediation adapter 6.11.0.0 release

- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleNativeAd.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleConstants.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleUtils.m
- adapters/Vungle/VungleAdapter/GADMediationAdapterVungle.m
Verified compatibility with Vungle SDK 6.12.0
Native ads Bidding support.
Rewarded interstitial ad Support.
> Vungle mediation adapter 6.12.0.0 release

- adapters/Fyber/FyberAdapter/GADMAdapterFyberBannerAd.m
- adapters/Fyber/FyberAdapter/GADMAdapterFyberInterstitialAd.m
- adapters/Fyber/FyberAdapter/GADMAdapterFyberRewardedAd.m
- updated google adapters to be compatible with DT Exchange iOS SDK version 8.1.6: modified ad targeting data assignment way according to SDK changes (global SDK assignment instead of per-request);
- fixed identation
> DT Exchange iOS SDK version 8.1.6 (updated)

- adapters/Pangle/PangleAdapter/Bidding/GADPangleRTBNativeRenderer.m
Fix main thread was stuck caused by `[NSData dataWithContentsOfURL:url]`
> fix  main thread was stuck

- adapters/Vungle/VungleAdapter.xcodeproj/project.pbxproj
- adapters/Vungle/VungleAdapter/Bidding/GADMAdapterVungleBiddingRouter.m
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleBanner.h
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleBanner.m
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleInterstitial.m
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleNativeAd.m
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleRewardedAd.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleBanner.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleInterstitial.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRewardBasedVideoAd.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleUtils.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleUtils.m
- adapters/Vungle/VungleAdapter/GADMediationAdapterVungle.m
* This commit re-adds the bidding banner class.
> [Vungle / 6.12.1.0] This commit re-adds the bidding banner class. (#62)

- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleConstants.h
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleUtils.m
> [Liftoff Monetize] 7.2.1.0

- adapters/Pangle/PangleAdapter/GADMediationAdapterPangle.m
update get bidding token string method
> update bidding token method

- adapters/IronSource/CHANGELOG.md
- adapters/IronSource/IronSourceAdapter/GADMAdapterIronSourceConstants.h
- adapters/IronSource/IronSourceAdapter/GADMAdapterIronSourceInterstitialAd.m
Added support for ironSource bidding ads.
> Added support for ironSource bidding ads.

- adapters/Line/LineAdapter/GADMediationAdapterLineRewardedAdLoader.m
> Added bidding ads.

- adapters/InMobi/InMobiAdapter/GADMAdapterInMobiBannerAd.m
- adapters/InMobi/InMobiAdapter/GADMAdapterInMobiConstants.h
- adapters/InMobi/InMobiAdapter/GADMAdapterInMobiInterstitialAd.m
- adapters/InMobi/InMobiAdapter/GADMAdapterInMobiRewardedAd.m
* Change init of IMWatermark
* version update
> InMobi Watermark init function renaming 

- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/Bidding/GADMediationVungleBanner.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleUtils.h
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleUtils.m
> InLine ads support for adMob. (#72)

- AdapterUnitTests/MolocoAdapterTests/Fakes/FakeMolocoInterstitial.swift
- AdapterUnitTests/MolocoAdapterTests/Fakes/FakeMolocoInterstitialFactory.swift
- AdapterUnitTests/MolocoAdapterTests/MolocoInterstitialAdTest.swift
- adapters/MolocoAdapter/CHANGELOG.md
- adapters/MolocoAdapter/MolocoAdapter/InterstitialAdLoader.swift
- adapters/MolocoAdapter/MolocoAdapter/MolocoAdapterErrorCode.swift
#MolocoAdapter Implement InterstitialAdLoader load and present methods and Moloco's interstitial ad event callbacks.
> #MolocoAdapter Implement InterstitialAdLoader load and present methods and Moloco's interstitial ad event callbacks.

- AdapterUnitTests/MolocoAdapterTests/Fakes/FakeMolocoRewarded.swift
- AdapterUnitTests/MolocoAdapterTests/Fakes/FakeMolocoRewardedFactory.swift
- AdapterUnitTests/MolocoAdapterTests/MolocoRewardedAdTest.swift
- adapters/MolocoAdapter/MolocoAdapter/RewardedAdLoader.swift
Implement Moloco Adapter's Show and Fail to Show
> Implement Moloco Adapter's Show and Fail to Show

- AdapterUnitTests/LiftoffMonetizeAdapterTests/AUTLiftoffMonetizeUtilsTests.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/Bidding/GADMediationVungleNativeAd.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleRouter.m
- adapters/LiftoffMonetize/Public/Headers/VungleAdNetworkExtras.h
Optimization in SDK initialization
Update OMSDK to version 1.5.0
Bug fixes and stability improvements
> 7.4.1 Vungle SDK release

- AdapterUnitTests/AdapterUnitTests.xcodeproj/project.pbxproj
- AdapterUnitTests/MolocoAdapterTests/Fakes/FakeMolocoBidTokenGetter.swift
- AdapterUnitTests/MolocoAdapterTests/MolocoMediationAdapterTest.swift
- adapters/MolocoAdapter/CHANGELOG.md
- adapters/MolocoAdapter/MolocoAdapter.xcodeproj/project.pbxproj
- adapters/MolocoAdapter/MolocoAdapter/MolocoBidTokenGetter.swift
- adapters/MolocoAdapter/MolocoAdapter/MolocoMediationAdapter.swift
- adapters/MolocoAdapter/MolocoAdapter/MolocoSdkImpl.swift
#Adapter #iOS Add collectSignals() implementation to Moloco adapter.
> #Adapter #iOS Add collectSignals() implementation to Moloco adapter.

- AdapterUnitTests/AdapterUnitTests.xcodeproj/project.pbxproj
- AdapterUnitTests/MolocoAdapterTests/Fakes/FakeMolocoAgeRestrictedSetter.swift
- AdapterUnitTests/MolocoAdapterTests/MolocoMediationAdapterTest.swift
- adapters/MolocoAdapter/MolocoAdapter.xcodeproj/project.pbxproj
- adapters/MolocoAdapter/MolocoAdapter/MolocoAgeRestrictedSetter.swift
- adapters/MolocoAdapter/MolocoAdapter/MolocoMediationAdapter.swift
- adapters/MolocoAdapter/MolocoAdapter/MolocoSdkImpl.swift
#Moloco #Adapter Set isAgeRestrictedUser bit on Moloco.
> #Moloco #Adapter Set isAgeRestrictedUser bit on Moloco.

- AdapterUnitTests/MintegralAdapterTests/AUTMintegralRTBAppOpenAdTests.m
- AdapterUnitTests/MintegralAdapterTests/AUTMintegralRTBBannerAdTests.m
- AdapterUnitTests/MintegralAdapterTests/AUTMintegralRTBInterstitialAdTests.m
- AdapterUnitTests/MintegralAdapterTests/AUTMintegralRTBNativeAdTests.m
- AdapterUnitTests/MintegralAdapterTests/AUTMintegralRTBRewardedAdTests.m
- AdapterUnitTests/MintegralAdapterTests/AUTMintegralWaterfallAppOpenAdTests.m
- AdapterUnitTests/MintegralAdapterTests/AUTMintegralWaterfallBannerAdTests.m
- AdapterUnitTests/MintegralAdapterTests/AUTMintegralWaterfallInterstitialAdTests.m
- AdapterUnitTests/MintegralAdapterTests/AUTMintegralWaterfallNativeAdTests.m
- AdapterUnitTests/MintegralAdapterTests/AUTMintegralWaterfallRewardedAdTests.m
- AdapterUnitTests/MintegralAdapterTests/MintegralAdapterTests.xctestplan
- adapters/Mintegral/CHANGELOG.md
- adapters/Mintegral/MintegralAdapter/GADMAdapterMintegralUtils.h
- adapters/Mintegral/MintegralAdapter/GADMAdapterMintegralUtils.m
- adapters/Mintegral/MintegralAdapter/GADMediationAdapterMintegral.m
> Added support for COPPA flag.

- AdapterUnitTests/AdapterUnitTests.xcodeproj/project.pbxproj
- AdapterUnitTests/BidMachineAdapterTests/BidMachineNativeAdTests.swift
- AdapterUnitTests/BidMachineAdapterTests/FakeBidMachineClient.swift
- AdapterUnitTests/BidMachineAdapterTests/FakeNativeAdProxy.swift
- adapters/BidMachineAdapter/BidMachineAdapter.xcodeproj/project.pbxproj
- adapters/BidMachineAdapter/BidMachineAdapter/BidMachineAdapter.swift
- adapters/BidMachineAdapter/BidMachineAdapter/BidMachineAdapterError.swift
- adapters/BidMachineAdapter/BidMachineAdapter/BidMachineClient.swift
- adapters/BidMachineAdapter/BidMachineAdapter/NaitveAdProxy.swift
- adapters/BidMachineAdapter/BidMachineAdapter/NativeAdLoader.swift
- adapters/BidMachineAdapter/CHANGELOG.md
> Created BidMachine adapter

- AdapterUnitTests/AdapterUnitTests.xcodeproj/project.pbxproj
- AdapterUnitTests/PubMaticTests/FakeOpenWrapSDKClient.swift
- AdapterUnitTests/PubMaticTests/PubMaticBannerViewTests.swift
- adapters/PubMatic/PubMaticAdapter/BannerAdLoader.swift
- adapters/PubMatic/PubMaticAdapter/OpenWrapSDKClient.swift
- adapters/PubMatic/PubMaticAdapter/PubMaticAdapter.swift
Implemented banner, interstitial, and rewarded ads
> Implemented banner, interstitial, and rewarded ads

- AdapterUnitTests/AdapterUnitTests.xcodeproj/project.pbxproj
- AdapterUnitTests/PubMaticTests/FakeNativeAd.swift
- AdapterUnitTests/PubMaticTests/FakeNativeAdProxy.swift
- AdapterUnitTests/PubMaticTests/FakeOpenWrapSDKClient.swift
- AdapterUnitTests/PubMaticTests/PubMaticNativeAdTests.swift
- adapters/PubMatic/PubMaticAdapter.xcodeproj/project.pbxproj
- adapters/PubMatic/PubMaticAdapter/BannerAdLoader.swift
- adapters/PubMatic/PubMaticAdapter/NativeAdLoader.swift
- adapters/PubMatic/PubMaticAdapter/NativeAdProxy.swift
- adapters/PubMatic/PubMaticAdapter/OpenWrapSDKClient.swift
- adapters/PubMatic/PubMaticAdapter/PubMaticAdapter.swift
- adapters/PubMatic/PubMaticAdapter/PubMaticAdapterError.swift
- adapters/PubMatic/PubMaticAdapter/Util.swift
> Add native ad implementation.

- adapters/InMobi/InMobiAdapter/GADMAdapterInMobiBannerAd.m
- adapters/InMobi/InMobiAdapter/GADMAdapterInMobiUnifiedNativeAd.m
- adapters/InMobi/InMobiAdapter/GADMediationAdapterInMobi.m
> InMobi - support for Interstitial rewarded & minor improvements

- .github/workflows/example.yaml
> Internal changes.
