googleads/googleads-mobile-ios-mediation

- adapters/Facebook/FacebookAdapter/GADFBBannerAd.m
- adapters/Facebook/FacebookAdapter/GADFBInterstitialAd.m
- adapters/Facebook/FacebookAdapter/GADFBNativeAd.m
- adapters/Facebook/FacebookAdapter/GADFBRewardedVideoAd.m
Update FAN Adapter to include AdMob SDK Version as mediation service flag for reporting. It is using FBAdSettings from Audience Network SDK.
> Set mediation service for Facebook adapter

- adapters/AdColony/Public/Headers/GADMAdapterAdColonyExtras.h
This is a Unity specific nit. 
If you're building an iOS Unity project with this adapter included, the default behavior is to building without support for '@import' ('Enable Modules' setting in Build Settings). So the default build won't compile until you make the change I'm proposing, or enable modules in settings. Not a huge deal, but unless there's a reason to use '@import' instead of '#import', this cleans up the experience of using this adapter in Unity!
> Use #import instead of @import

- adapters/MoPub/MoPubAdapter/GADMAdapterMoPub.m
- adapters/MoPub/MoPubAdapter/MoPubAdapterMediatedNativeAd.m
* As of MoPub 5.0.0, keywords needed to be separate into two APIs based on whether they contain personally identifiable information.
* Initialize the MoPub SDK in the adapter with a valid ad unit ID from the publisher's app.
> Separate keywords passing + Initialize MoPub

- adapters/InMobi/InMobiAdapter/InMobiMediatedNativeAppInstallAd.m
Updated `InMobiMediatedNativeAppInstallAd` initialization method.
- Simplified `init` method by extracting into few methods.
- Added additional check to prevent this crash: https://github.com/googleads/googleads-mobile-ios-mediation/issues/50
- Ensured that callback is in the main thread.
- Fallback to default Xcode code formation
> Simplify InMobiMediatedNativeAppInstallAd init

- adapters/MoPub/MoPubAdapter/MoPubAdapterMediatedNativeAd.m
This is to fix the MoPub privacy info icon image not shown due to wrong attribute name.
> kAdIconImageKey --> kPrivacyIconImageName

- adapters/Facebook/CHANGELOG.md
- adapters/Facebook/FacebookAdapter/GADFBNativeAd.m
- adapters/Facebook/FacebookAdapter/GADMAdapterFacebook.m
Preparing adapter for Facebook Audience Network 5.2.0. This adapter works with the Beta SDK which can be downloaded from https://developers.facebook.com/docs/audience-network/sdk-beta-program.
This PR includes: 
* Replacing FBAdChoicesView with FBAdOptionsView.
* Bumping up adapter version.
> Updating Facebook Adapter to version 5.2.0.0

- adapters/AdColony/AdColonyAdapter/GADMAdapterAdColony.m
- adapters/AdColony/AdColonyAdapter/GADMAdapterAdColonyInitializer.h
- adapters/AdColony/AdColonyAdapter/GADMAdapterAdColonyInitializer.m
- adapters/AdColony/AdColonyAdapter/GADMAdapterAdColonyRewardedAd.h
- adapters/AdColony/AdColonyAdapter/GADMAdapterAdColonyRewardedAd.m
- adapters/AdColony/AdColonyAdapter/GADMediationAdapterAdColony.m
- adapters/AdColony/CHANGELOG.md
Updating AdColony adapter to fix a crash in case of failed to fetch rewarded ad.
> Updating AdColony adapter to fix a crash in case of failed to fetch rewarded ad.

- adapters/Facebook/CHANGELOG.md
- adapters/Facebook/FacebookAdapter/GADMAdapterFacebookConstants.h
- adapters/Facebook/FacebookAdapter/GADMediationAdapterFacebook.m
This version removes a dependency on CoreLocation.framework and fixes minor bugs.
https://developers.facebook.com/docs/audience-network/changelog-ios#5_3_2
> Update Facebook adapter to version 5.3.2.0

- adapters/Oath/BuildScript/README.md
- adapters/Oath/OathAdapter.xcodeproj/project.pbxproj
- adapters/Oath/OathAdapter/GADMAdapterNexage.h
- adapters/Oath/OathAdapter/GADMAdapterNexage.m
- adapters/Oath/OathAdapter/GADMVASAdapterBaseClass.h
- adapters/Oath/OathAdapter/GADMVASAdapterBaseClass.m
- adapters/Oath/OathAdapter/GADMediationAdapterVerizon.h
- adapters/Oath/OathAdapter/GADMediationAdapterVerizon.m
- adapters/Oath/README.md
This pull request replaces #102. Please note that the adapter must be used with Verizon Ads SDK v1.0.3.
> Adding Oath (Verizon Ads SDK) Adapter v1.0.3.0

- adapters/Fyber/CHANGELOG.md
- adapters/Fyber/FyberAdapter/GADMAdapterFyberConstants.h
- adapters/Fyber/FyberAdapter/GADMAdapterFyberUtils.m
Update the adapter to version 7.5.1
Fixed bug: calling `dispatch_sync(dispatch_get_main_queue()` caused crash. There is no need to do it on the main thread since the init flow will continue with another thread anyway.
> Updating Fyber Adapter to version 7.5.1

- adapters/Facebook/CHANGELOG.md
- adapters/Facebook/FacebookAdapter/GADFBUtils.m
Correct mapping of tagForChildDirectedTreatment to setMixedAudience in Facebook adapter
> Correct mapping of tagForChildDirectedTreatment to setMixedAudience in Facebook adapter

- adapters/Vungle/CHANGELOG.md
- adapters/Vungle/VungleAdapter/GADMAdapterVungleConstants.h
Vungle AdMob Adapter 6.7.1.0 is compatible with Vungle SDK 6.7.1.
> Vungle AdMob Adapter 6.7.1.0

- adapters/Vungle/CHANGELOG.md
- adapters/Vungle/VungleAdapter/GADMAdapterVungleConstants.h
This version of the adapters has been certified with Vungle 6.8.0.
> Release 6.8.0.0 Vungle AdMob Adapter 

- adapters/AppLovin/AppLovinAdapter.xcodeproj/project.pbxproj
Chartboost iOS SDK 8.3.0 has been released today.
I'm creating this PR to keep track of the new adapters release we need, although the only change is a version number bump.
> Chartboost 8.3.1 support

- adapters/MyTarget/CHANGELOG.md
- adapters/MyTarget/MyTargetAdapter/GADMAdapterMyTarget.m
- adapters/MyTarget/MyTargetAdapter/GADMAdapterMyTargetConstants.h
- adapters/MyTarget/MyTargetAdapter/GADMAdapterMyTargetRewardedAd.m
Supported GoogleMobileAds 7.66.0 and myTarget 5.9.2
> Updating myTarget iOS Adapter to version 5.9.2.0

- adapters/Unity/UnityAdapter/GADMAdapterUnity.m
This pr is to add back the if check for completion handler which we previously added in the [pr](https://github.com/googleads/googleads-mobile-ios-mediation/pull/270/files#diff-3049d5d2e2115b254321aef39709c848cccde2e9956eef921f4776817cc68cefR195). 
As this completion handler could be null in many cases, without the check it causes app crash for many users.
> Add completion handler null check to prevent crash

- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
This PR is enabling background downloading by default in 6.9.1.0 Vungle Adapter.
> Enable background downloading by default in Vungle Adapter

- adapters/Vungle/CHANGELOG.md
- adapters/Vungle/VungleAdapter/GADMAdapterVungleConstants.h
This version of the adapter has been certified with Vungle 6.9.2 SDK.
> Release 6.9.2.0 Vungle AdMob Adapter

- adapters/Vungle/CHANGELOG.md
- adapters/Vungle/VungleAdapter/GADMAdapterVungleConstants.h
This version of the adapter has been certified with Vungle 6.10.0 SDK.
> Release 6.10.0.0 Vungle AdMob Adapter

- adapters/Nend/NendAdapter/GADMAdapterNend.m
Fixes: Not called adDidRecordClick: delegate method when interstitial ads clicked by Google Mobile Ads SDK v8.7.0 or higher.
> Nend Adapter: call adapterDidGetAdClick: when interstitial ads clicked.

- adapters/Fyber/FyberAdapter/GADMAdapterFyberRewardedAd.m
We need to do this change in order to resolve some discrepancy issues. In Fyber's SDK, the video must be completed in order to call IADidReward.
> <Fyber> Moved [_delegate didEndVideo] from IAVideoCompleted to IADidReward

- adapters/Vungle/Public/Headers/VungleAdNetworkExtras.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleConstants.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
- adapters/Vungle/VungleAdapter/VungleAdNetworkExtras.m
- Verified compatibility with Vungle SDK 6.10.4.
- Fixed issue with the adapter not respecting muted settings on the dashboard when the boolean in networkExtras is not explicitly set.
> Vungle mediation adapter 6.10.4.0 release

- adapters/Vungle/Public/Headers/VungleAdapter.h
- adapters/Vungle/VungleAdapter.xcodeproj/project.pbxproj
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleBanner.h
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleBanner.m
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleInterstitial.h
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleInterstitial.m
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleRewardedAd.h
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleRewardedAd.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleBanner.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleConstants.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleDelegate.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleInterstitial.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRewardBasedVideoAd.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRewardBasedVideoAd.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
- adapters/Vungle/VungleAdapter/GADMediationAdapterVungle.h
- adapters/Vungle/VungleAdapter/GADMediationAdapterVungle.m
Adding the Open Bidding implementation to the AdMob adapter. GADMediationAdapterVungle now implements GADRTBAdapter instead of GADMediationAdapter. The VungleRouter implements the new VungleSDKHBDelegate. The Banner and Interstitial classes now implement their respective Mediation classes. The old interstitial class needs to remain as a router to the real adapter class, similar to the old rewarded class. The new ad format classes are moved under "Bidding". The legacy classes remain for waterfall cases. (#33)
Adding the Open Bidding implementation to the AdMob adapter. GADMediationAdapterVungle now implements GADRTBAdapter instead of GADMediationAdapter. The VungleRouter implements the new VungleSDKHBDelegate. The Banner and Interstitial classes now implement their respective Mediation …
> Vungle Bidding

- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleNativeAd.m
This commit will add implementation for the optional methods `handlesUserClicks` and `handlesUserImpressions` for native ad as requested by Google.
> [Vungle] This commit will add implementation for the optional methods for native ad 

- adapters/Unity/UnityAdapter/GADMAdapterUnity.m
- adapters/Unity/UnityAdapter/GADMediationAdapterUnity.m
To improve fill expectation issues, enhance tracking and provide sequential caching, we must add Object ID to load and show request of an Ad Unit.
This PR is to add a UUID when issuing Load request and use the same (as object ID) when doing the Show call later.
Manually tested in Waterfall that we send Load and Show options as expected in the adapter.
> [UnityAds] Add objectId for all Load/Show API calls

- adapters/DTExchange/DTExchangeAdapter/GADMAdapterFyberConstants.h
- adapters/DTExchange/DTExchangeAdapter/GADMAdapterFyberRewardedAd.m
- adapters/DTExchange/DTExchangeAdapter/GADMAdapterFyberUtils.m
@joshh-devrel please approve this.
This is **mandatory** support for the version DTExchange **8.2.1**.
However this adapter version **should be used with 8.2.0 SDK** as well, please merge it instead of: https://github.com/googleads/googleads-mobile-ios-mediation/pull/407 and https://github.com/googleads/googleads-mobile-ios-mediation/pull/408
Please be noted this is our new official fork, the previous Fyber Engineering account is not relevant anymore.
@TomerFyber FYI
> DTExchange 8.2.0 version support

- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/Bidding/GADMediationVungleBanner.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/Bidding/GADMediationVungleInterstitial.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/Bidding/GADMediationVungleNativeAd.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/Bidding/GADMediationVungleRewardedAd.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleConstants.h
Please verify the watermark functionality.
We inserted the iOS code from the Ads Identification Technology Guide, but also set the alpha value of the UIImage to be 0.03 because the guide stated that `The opacity of the overlay will not exceed 3%` and there's a `TODO` about verifying the alpha value in the sample code.
[Vungle -  Ads Identification Technology Guide.pdf](https://github.com/googleads/googleads-mobile-ios-mediation/files/11841264/Vungle.-.Ads.Identification.Technology.Guide.pdf)
> Updating Vungle iOS Adapter v7.0.1.0. Adding watermark support

- adapters/Unity/UnityAdapter/AdNetworkAdapterProxy/GADMUnityBannerNetworkAdapterProxy.m
- adapters/Unity/UnityAdapter/MediationAdapterProxy/GADUnityBaseMediationAdapterProxy.m
In Unity Ads 4.8.0, we are adding a new bannerViewDidShow callback to our banner listener to more accurately report impressions.
Added bannerViewDidShow to the delegate in GADMUnityBannerNetworkAdapterProxy
Added bannerViewDidShow to the delegate in GADUnityBaseMediationAdapterProxy and called reportAdImpression
> [Unity Ads 4.8.0] Adding usage of bannerDidShow callback to report impressions

- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/Bidding/GADMediationVungleBanner.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/Bidding/GADMediationVungleInterstitial.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/Bidding/GADMediationVungleNativeAd.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/Bidding/GADMediationVungleRewardedAd.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleBanner.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleConstants.h
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleInterstitial.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleRewardBasedVideoAd.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleRouter.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleUtils.h
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleUtils.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMediationAdapterVungle.h
The Liftoff error codes has been added to public documentation.
Please update Google's public documentation for Liftoff SDK to refer to this page for the error codes:
https://support.vungle.com/hc/en-us/articles/15661036969627
Thanks.
> [Liftoff Monetize] 7.2.0.0 - Update error objects to use the Liftoff errors where applicable

- adapters/DTExchange/DTExchangeAdapter/GADMAdapterFyberUtils.m
Hi! Please merge this PR into nearest Google Adapter for DTExchange SDK, since we are gonna deprecate this API, starting from future version 8.3.3.
Thanks in advance.
> DTExchange SDK: removed keywords support

- AdapterUnitTests/AppLovinAdapterTests/AUTAppLovinAdapterTests.m
- adapters/AppLovin/AppLovinAdapter/GADMediationAdapterAppLovin.m
- adapters/AppLovin/CHANGELOG.md
- adapters/AppLovin/Public/Headers/GADMediationAdapterAppLovin.h
- Replaced the deprecated AppLovin SDK's bid token collection API with its new one.
- Replaced the deprecated AppLovin SDK's initialization APIs with its new APIs.
- Prevented multiple initializations of AppLovin SDK when multiple AppLovin SDK keys are provided.
> - Replaced the deprecated AppLovin SDK's bid token collection API with its new one.

- AdapterUnitTests/AdapterUnitTests.xcodeproj/project.pbxproj
- AdapterUnitTests/MolocoAdapterTests/Fakes/FakeMolocoNativeAd.swift
- AdapterUnitTests/MolocoAdapterTests/Fakes/FakeMolocoNativeAssets.swift
- AdapterUnitTests/MolocoAdapterTests/MolocoNativeAdTest.swift
- adapters/Moloco/MolocoAdapter/NativeAdLoader.swift
Changes
- Adding required Native Ad Assets validation tests
- And corrected a bug that it Uncovered: 
- The conversion logic from Double to NSDecimal Number was not working.
-  Passed the new and Existing tests.
> Native Assets test and a bug fix in StarRating computation.
